version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  update-algolia-index:
    executor: with-chrome-and-firefox
    steps:
      - checkout
      - run: yarn install
      - run: yarn update-algolia-index

workflows:
  build-and-test:
    jobs:
      - cypress/run:
          package-manager: "yarn"
          install-browsers: true
          post-install: "yarn cypress info && yarn types && yarn lint && yarn test:unit"
          start-command: "yarn start"
          cypress-command: "npx cypress run --browser chrome"
          post-steps:
            - run:
                name: Check for Broken Links
                command: "yarn check:links"
      - cypress/run:
          package-manager: "yarn"
          install-browsers: true
          post-install: "yarn cypress info && yarn types && yarn lint && yarn test:unit"
          start-command: "yarn start"
          cypress-command: "npx cypress run --browser chrome --config viewportWidth=375,viewportHeight=667"
          post-steps:
            - run:
                name: Check for Broken Links
                command: "yarn check:links"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - update-algolia-index
