version: 2.1

orbs:
  cypress: cypress-io/cypress@1.28.0

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node16.14.2-slim-chrome100-ff99-edge"
    resource_class: medium+

jobs:
  update-algolia-index:
    executor: with-chrome-and-firefox
    steps:
      - checkout
      - run: yarn install
      - run: yarn update-algolia-index

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          name: "Setup Linux"
          yarn: true
          executor: with-chrome-and-firefox
          build: "yarn build"
          post-steps:
            - run:
                name: Print machine info ℹ️
                command: yarn cypress info
            - run:
                name: Check Types
                command: yarn types
            - run:
                name: Lint Files
                command: yarn lint
            - run:
                name: Run Unit Tests
                command: yarn test:unit

      # Run E2E tests in Chrome
      - cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          requires:
            - Setup Linux
          post-steps:
            - run:
                name: Check for Broken Links
                command: yarn check:links

      # Run E2E tests in Chrome with mobile viewport
      - cypress/run:
          name: "UI Tests - Chrome - Mobile"
          browser: chrome
          config: "viewportWidth=375,viewportHeight=667"
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start
          requires:
            - Setup Linux

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - update-algolia-index
